#!/bin/bash

# INSTALLING MINICONDA #

# UN-INSTALLING MINICONDA #
rm -rf ~/miniconda3/
rm -rf ~/.conda
rm  ~/.condarc

## remove the conda block from your ~/.profile or ~/.bashrc

# creating a new environment
conda create --name <my_env>

# remove an environment
conda env remove -n <my_env>

# search for packages
conda search -c bioconda <package>

# search for packages in already installed environments
conda search --envs <package>
mamba search --envs <package>

# installing a packages in an environment
conda install -c bioconda -n <my_env> <package>=<version> <package>=<version>
## 'bioconda' is a specific 'channel' of conda packages
# mamba is a lot faster at resolving environments!
mamba install -c bioconda -n <my_env> <package>=<version> <package>=<version>

# install many packages at the same time using a YAML file
conda env create -n <my_env> -f <env.yml>

# activate and deactivate a certain environment
conda activate <my_env>
conda deactivate

# list all packages installed in an environment
conda list

# update a package within the environment
conda update <package>
mamba update <package>

# checkout the history of an environment
## package upgrades / downgrades, additions, removals etc
conda list -n <my_env> -r # -r is short for --revisions

# get info of versions and build numbers of packages
conda search -c bioconda <package> --info
mamba search -c bioconda <package> --info

# remova a package from an environment
conda remove <package>

# list all environments
conda env list

# INSTALLING PERL MODULES WITH CONDA

## install the module LWP:Simple
conda install perl-lwp-simple
## so essentially replace ':' in module name with '-',
## lower case everything, and add 'perl-'
