#!/bin/bash

# list active containers
docker container ls

# list available images
docker images

# remove an image
docker image rm my_image_id:tag

# given an active container, open a shell
## this is useful for checking the file directory tree inside the container
docker exec -it my_container_hash /bin/bash

# mount a workdir ('home/jmartijn/test_dir') on your system, to a dir inside the container ('/data')
docker run -v /home/jmartijn/test_dir:/data my_container_or_image

