#!/usr/bin/env python

# argparse

# load argparse
import argparse

# start the argument parser
parser = argparse.ArgumentParser(
            description=
        '''
        some description of your script
        ''')

# add arguments
parser.add_argument(
        "-g", "--gff3",
        dest='gff3_file',
        type=str,
        required=True,
        help="Input GFF3 genome file")
## -g is the short option
## --gff3 is the long option
## value of option is held in args.gff3_file
## type=str defines its a string
## required=True defines the script needs this argument to work
## help="..." is the text displayed when running script with -h

parser.add_argument(
        "-w", "--window_size",
        dest='wdw_size',
        type=int,
        required=False,
        default=3,
        help="Window size for determining high-cov regions")
## example of a integer option
## required=False defines that this is an optionable argument
## if it is not stated, it will have default value 3

# collect arguments in args
args = parser.parse_args()

