#!/usr/bin/env python

# matplotlib - a library for plotting stuff

import matplotlib.pyplot as plt

# a simple histogram

## if data is a simple list of numbers...
plt.hist(data, bins=30, edgecolor='black')
# edgecolor = color of bar edges

# add labels and title
plt.xlabel('Relative intron location')
plt.ylabel('Frequency')
plt.title('Histogram')

# save file
plt.savefig('histogram.png')

# show when executing python script
plt.show()


# two histograms stacked on top of one another

# create a figure with two subplots, stacked vertically
fig, axs = plt.subplots(2, 1)
# 2 rows, 1 column

# plot the histograms
axs[0].hist(data1, bins=30)
axs[1].hist(data2, bins=30)

# add titles and axis labels
axs[0].set_title('Histogram of data1')
axs[1].set_title('Histogram of data2')
axs[1].set_xlabel('Values')
axs[0].set_ylabel('Frequency')
axs[1].set_ylabel('Frequency')

# adjust the space between subplots
plt.subplots_adjust(hspace=0.4)
